### PR TITLE
Add GGPL 1.2 with new features

### PR DESCRIPTION
**Pull request by GoombaProgrammer**
1. Fixed typo
2. Add information about what to do when someone evades the license

### CODE REVIEW

**Comment by GoldenretriverYT** [comment]
hello what typo was fixed?

**Comment by GoombaProgrammer** [comment]
what ever is now whatever

**Comment by GoldenretriverYT** [comment]
please ed sheeran the typo back in. typos are very impotant for the lisense to be a propar lisense.

**Comment by GoombaProgrammer** [comment]
K done

**Comment by GoldenretriverYT** [comment]
LATM. (looks awesome to me)

**Pull request merged**
